export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Login } from "./Login";
export { default as Logout } from "./Logout";
export { default as Register } from "./Register";
export { default as Classes } from "./Classes";
export { default as Pricing } from "./Pricing";
export { default as Admin } from "./Admin";
